name: CI

on:
  push:
    branches-ignore: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Maven
        run: mvn -T 1C -B dependency:go-offline
      - name: Build with Maven
        run: mvn -T 1C -B package -Pbuild-extras --file pom.xml
