name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - src/**
      - pom.xml
      - LICENSE.txt
      - .github/workflows/build_deploy.yml

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: glowstone-upstream
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Maven
        run: mvn -T 1C -B dependency:go-offline
      - name: Maven Build and Deploy
        run: mvn -T 1C -B source:jar javadoc:jar deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
